version: '3.3'

services:
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./:/www
    environment:
      - ROOT_PATH=/www/
    env_file:
      - .env
